- name: Delete a namespace
  k8s:
    kubeconfig: "{{ kubeconfig_file }}"
    context: "{{ kubeconfig_context }}"
    name: "{{ delete_ns_name }}"
    api_version: v1
    kind: Namespace
    state: absent
