- name: Create a k8s namespace
  k8s:
    kubeconfig: "{{ kubeconfig_file }}"
    context: "{{ kubeconfig_context }}"
    name: "{{ create_ns_name }}"
    api_version: v1
    kind: Namespace
    state: present
